### ISSUE TITLE
Home screen appears to be moved upwards and cut in half while returning from other apps

### ISSUE THREAD

**Issue by praveenchandranpk** [8bitPit/Niagara-Issues#1185]
![Screenshot_20200216-195647](https://user-images.githubusercontent.com/50801972/74606506-02a91100-50f7-11ea-9258-bcd4e811432e.jpg)

It happens many times while i return to the home screen from any other app. I have to press the home button again to get it back to normal. I'm seeing this bug in the past 2 or 3 versions. Currently I'm on the latest version v 0.15.2 from telegram. My phone is oneplus 5t android 9 version.

**Comment by 8bitPit** [comment]
Fixed in v.0.24

**Comment by luxcalor** [comment]
Still happens from time to time

**Comment by praveenchandranpk** [comment]
Me too having the same issue. It's an old issue still not resolved.

**Comment by 8bitPit** [comment]
I see, thanks for reporting guys! I couldn't find a way to reproduce this reliably yet. But I'll try further after release.

**Comment by 8bitPit** [comment]
Does the issue still happen on your device? If so, please let me know :)
