### ISSUE TITLE
Support work profile calendar events

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1400]
Since Android 10, work profiles can let main profile apps access work profile calendars. Note: The organization of the profile has to allow that: "Both admins and users must enable this feature before the experience will become available on a user’s work Calendar app." [[Source]](https://workspaceupdates.googleblog.com/2020/11/view-your-personal-and-work-calendars.html)

**Comment by gaara87** [comment]
This would be immensely helpful for more widespread adoption. Work profiles usually imply something very crucial and it being easily inaccessible is quite problematic. Big +1 on this :) As a fellow android dev, i'm happy to help

**Comment by saadismail** [comment]
+1 on this, this feature would be immensely helpful.

**Comment by PumaRV** [comment]
2 years have passed, please make this happen 🙏

**Comment by janvanveldhuizen** [comment]
Any news?

**Comment by 8bitPit** [comment]
@janvanveldhuizen I'm sorry, we haven't started working on work profile calendar events yet. For now, I recommend manually sharing your work profile events with your private account so that they'll become visible in Niagara Launcher.

**Comment by PumaRV** [comment]
> @janvanveldhuizen I'm sorry, we haven't started working on work profile calendar events yet. For now, I recommend manually sharing your work profile events with your private account so that they'll become visible in Niagara Launcher.

That's very sad to hear, doing completely defeats the purpose of having separate profiles.

**Comment by janvanveldhuizen** [comment]
Thanks for the reply. But company policy doesn't let us share anything from the Google environment, like calendar events, outside the domain. The whole idea of a work profile is to keep everything in a safe zone.
Anyway, I get that you have to set priorities. Keep up the good work, and I hope to see this feature implemented at some point.

**Comment by lack** [comment]
I have the same issue.  I can export my work calendar in a way that shows blocks as "busy" but not any useful details.

**Comment by eruizc-dev** [comment]
I'd be extremely interested in this feature, as of today I must have two calendar widgets which requires an active effort to see if there's something in the other calendar that I may be missing and looks really ugly

**Comment by irishtexmex** [comment]
+1. Just adding my voice to the list of users that have been quietly monitoring this for a while. Would LOVE to see this integrated!

FWIW, I'm one of the MDM admins at my company & can speak in more detail about work profiles if needed.

**Comment by 8bitPit** [comment]
Hey everyone, I have some good and bad news.
The good news is that we plan to release this feature soon.
The bad news is that your company is unlikely to allow cross-profile calendars. Our feature requires the device admin to grant the "cross-profile calendar" permission/policy for Niagara Launcher or all apps. If you're a device admin and use Google Workspace, [here's](https://workspaceupdates.googleblog.com/2022/09/google-endpoint-management-personal-work-calendars-android.html) how to do that. By the way, this permission is not related to the feature that lets you access personal events from your Google Calendar work app (I'm talking about [this feature](https://workspaceupdates.googleblog.com/2020/11/view-your-personal-and-work-calendars.html)). If you can already see personal events in your work profile calendar, this does not necessarily mean that your administrator granted cross-profile calendar events.

**Comment by 8bitPit** [comment]
Implemented in [v1.12](https://github.com/8bitPit/Launcher/releases). Fingers crossed, you can get the necessary permissions to get it working on your device! We also published a help article which is basically a reworded version of my last reply but we'll add more info and troubleshooting tips based on your feedback and what we can find out; unfortunately, the calendar work profile API is sparsely documented and I don't know of any other app that uses it: https://github.com/8bitPit/Launcher/releases.

**Comment by irishtexmex** [comment]
Unfortunately still not seeing the work calendars show up when I go to _Niagara widget settings > Calendar > **Filter events_**

Attached are screenshots from my phone's Calendar app's setting & from my work's MDM console.

![image](https://github.com/8bitPit/Niagara-Issues/assets/29881302/dc03ff62-da1f-4fbc-bd2d-f255f3d4227b)

<img width="1808" alt="image" src="https://github.com/8bitPit/Niagara-Issues/assets/29881302/4d97e6d8-1731-47b2-89af-c7235af583bd">

Let me know if there's debugging I can help provide, and/or if there is something else I may be missing in getting this set up.

Thank you in advance for all of your work on this feature! 🙏

**Comment by mikelward** [comment]
https://github.com/8bitPit/Launcher/releases is a 404. Is there a dedicated doc for this feature please?

**Comment by mikelward** [comment]
I eventually found https://help.niagaralauncher.app/article/170-work-profile-calendar. It doesn't say what steps I need to do as an end user, for example where to find the cross-profile settings, or how to tell if my domain administrator disabled that functionality.
