### ISSUE TITLE
Don't peek status bar when leaving search

### ISSUE THREAD

**Issue by 8bitPit** [8bitPit/Niagara-Issues#1432]
When swiping up to quit search, it doesn't make sense to show the status bar (if the user has hidden it).

![ezgif-5-88e0e65b044d](https://user-images.githubusercontent.com/9284845/101241704-dd72a700-36f8-11eb-9a9c-b727b2cce031.gif)

**Comment by Yudha20** [comment]
Any updates on this?

**Comment by 8bitPit** [comment]
Fixed in v.0.90.0 🎉

**Comment by Yudha20** [comment]
Hello, but the problem still persists in the latest version. What to do now?

**Comment by 8bitPit** [comment]
@Yudha20 I just checked again, and the status bar only peeks on the home screen and not in search, as intended. If your version behaves differently, can you please send a recording of the issue?

**Comment by Yudha20** [comment]
https://user-images.githubusercontent.com/70634559/103794316-99155680-506a-11eb-8500-19ead0a57584.mp4

This might help.

**Comment by Yudha20** [comment]
Hi, was this acknowledged?

**Comment by 8bitPit** [comment]
Sorry for the late reply, @Yudha20. I think you're experiencing the issue described here: https://github.com/8bitPit/Niagara-Issues/issues/1153. Your keyboard app might cause this, but we're not sure yet.

**Comment by Yudha20** [comment]
Hello, I tried using two different keyboards but the issue persisits.
