### ISSUE TITLE
Notification preview in Pop-ups gets stuck/glitched

### ISSUE THREAD

**Issue by Amorphous404** [8bitPit/Niagara-Issues#2192]
### Describe the bug

Notification previews in Pop-ups gets obscured by other apps & notifications, especially happens with apps that receive a high number of notifications like Twitter. 

**Workaround:** Force stop or Restart the Launcher.

### Steps to reproduce

Random behaviour.

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

-

### Android version

Android 5.0 (Lollipop)

### Screenshots / Screen recordings

![Screenshot_2023-02-03-19-10-33-75_965bbf4d18d205f782c6b8409c5773a4](https://user-images.githubusercontent.com/96917972/216617625-f9447cc1-51e1-4b46-b0dc-acb46a484a0d.jpg)

**Comment by JonDum** [comment]
I haven't been able to narrow down how to repro it yet, but if it might be helpful to note that it seems to happen most often with Twitter notifications. Twitter is in my top level favorites, but the visual glitch occurs with the notifications area open with Apps inside the pop-up folder.

**Comment by Amorphous404** [comment]
#1436

**Comment by JonDum** [comment]
![Screenshot_20230314-075216](https://user-images.githubusercontent.com/191920/225041772-0d9d695a-81b0-4802-893d-2e3c9a8e219b.png)

It's definitely swiping that causes it. The notification does not fully dismiss.

Can we get a at least get an update if devs are looking into it?

**Comment by 8bitPit** [comment]
Hey @JonDum & @Amorphous404, thank you both for reporting. I was able to replicate the problem and have fixed it. We plan to release a patch in early April, and the issue should be resolved by then.

**Comment by 8bitPit** [comment]
Fixed in [v.1.9](https://github.com/8bitPit/Niagara-Issues/releases). Technically, the issue can still occur. However, it will automatically disappear once you close the popup. Previously, the issue persisted until restart the whole launcher.

**Comment by JonDum** [comment]
Hi again.
Unfortunately, I am still experiencing this issue in v1.9
![Screenshot_20230507-172934](https://user-images.githubusercontent.com/191920/236710691-0e5fee28-755d-4edb-9a51-9ba27f5dbf53.png)
