### ISSUE TITLE
Search with Pinyin no longer works for Chinese app

### ISSUE THREAD

**Issue by kuoe0** [8bitPit/Niagara-Issues#2457]
### Describe the bug

Before this update, I can use the pinyin of the Chinese character to search the apps named in Chinese. But now, it doesn't work.

### Steps to reproduce

1. Install an app named in Chinese (e.g. https://play.google.com/store/apps/details?id=com.taobao.taobao&hl=zh_TW)
2. Search by 'T'

Expected: 淘宝 (Taobao) should be in the search result
Actual: 淘宝 (Taobao) is not in the search result

### Does the issue also occur with other 3rd-party launchers?

Not applicable

### Device name

Google Pixel 7 Pro

### Android version

Android 13

**Comment by 8bitPit** [comment]
Thank you for reporting @kuoe0. I am happy to tell you that we have already fixed the bug with v1.10.3: https://github.com/8bitPit/Niagara-Issues/releases. It's already available to download on GitHub, and we'll soon roll it out on Google Play.

**Comment by kuoe0** [comment]
I think it isn't fixed. I'm using 1.11.2 and still can't search by Pinyi.

**Comment by 8bitPit** [comment]
I see, thanks for the update. Niagara Launcher only enables Pinyin transliteration if you set Chinese as one of your languages under system settings (it doesn't have to be the primary language). Could that be the culprit?

**Comment by kuoe0** [comment]
I use Chinese as my primary language.

**Comment by 8bitPit** [comment]
Huh, that's weird. Could you check if executing this secret command fixes the issue for you? https://niagaralauncher.app/app-link/secret-command?cmd=refreshnames

**Comment by kuoe0** [comment]
No, the issue is still there. Let me know if you need more information!

**Comment by 8bitPit** [comment]
Thanks. We'll troubleshoot the issue and check if we can reproduce it.

**Comment by TFackler** [comment]
Taobao can be found as soon as you type more than one letter. For example, searching 'Ta' will find 淘宝. 

However, I think making this behavior more consistent so when you type 't', '淘宝' is included in the results is a good idea. So in the next update that should be the case :)

Thanks again for reporting this!

**Comment by kuoe0** [comment]
> Taobao can be found as soon as you type more than one letter. For example, searching 'Ta' will find 淘宝.

It works! Thx.

> However, I think making this behavior more consistent so when you type 't', ' 淘宝 ' is included in the results is a good idea. So in the next update that should be the case :)

Yeah, I think showing the all apps begins with 't' like when we scroll to 't' is a more consistent behavior. Thx!
