### ISSUE TITLE
Locking screen causes active application to go in background

### ISSUE THREAD

**Issue by codesalatdev** [8bitPit/Niagara-Issues#2570]
### Describe the bug

When I have an application open (e.g. Firefox) and lock my phone using the power button, the application is put in the background. When I unlock the screen again, I am seeing my home screen instead of the app that was open before.

This happens every time I lock my phone, though the problem only starts to appear some time after booting (few minutes). This does not occur on a Nothing Phone (1) with Android 13 non-pro Niagara, but is reproducible on my Nothing Phone (2) Android 14 with Niagara Pro.

I also tried reinstalling, resetting options (clearing storage) and restarting.
With ADB Logging, I can see the following lines appear while the screen is turning off:
```
01-24 21:45:45.849  3621  3621 I NT-OverviewComponentObserver: , mMyHomeIntent = Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 pkg=com.nothing.launcher cmp=com.nothing.launcher/com.android.searchlauncher.SearchLauncher }
01-24 21:45:45.857  3621  3621 I NT-OverviewComponentObserver: updateOverviewTargets: sourceIntent = null, defaultHome = ComponentInfo{bitpit.launcher/bitpit.launcher.ui.HomeActivity}, mIsHomeDisabled = false, mIsDefaultHome = false
01-24 21:45:45.859  3621  3621 I NT-OverviewComponentObserver: updateOverviewTargets:  [use fallback home] --> mIsHomeAndOverviewSame = false, mOverviewIntent = Intent { act=android.intent.action.MAIN cat=[android.intent.category.DEFAULT] flg=0x10000000 cmp=com.nothing.launcher/com.android.quickstep.RecentsActivity }
01-24 21:45:45.859  3621  3621 I NT-OverviewComponentObserver: , mCurrentHomeIntent = Intent { act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 cmp=bitpit.launcher/.ui.HomeActivity }
01-24 21:45:45.869  2482  5482 D NtPopUpViewImpl: PopUpView: onAppFocusChanged: newTask=Task{e6484f7 #6 type=home I=bitpit.launcher/.ui.HomeActivity}, showDimmer=false
01-24 21:45:45.871  2482  5482 I ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10000000 cmp=bitpit.launcher/.ui.HomeActivilauncherty} with LAUNCH_SINGLE_TASK from uid 10188 pid 3621 (BAL_ALLOW_ALLOWLISTED_COMPONENT) result code=2
```

As someone with only minimal knowledge about android, this looks like Niagara is coming into focus, which seemed relevant to me.

### Steps to reproduce

1. Open an application
2. Use the power button to lock the phone
3. Unlock the phone again
4. User is presented with the home screen instead of the currently opened app

### Does the issue also occur with other 3rd-party launchers?

Problem doesn't occur with other launchers

### Other 3rd-party launcher(s) tested

Nothing Launcher

### Device name

Nothing Phone (2)

### Android version

Android 14

### Screenshots / Screen recordings

https://github.com/8bitPit/Niagara-Issues/assets/10341765/671dfce6-5738-41e0-8410-247fe4caba5a

**Comment by DawnImpulse** [comment]
same issue occurring with me as well

**Comment by DawnImpulse** [comment]
I believe it has something to do with Nothing OS itself... the problem has now been fixed automatically... It was happening for past many weeks & today I noticed that it is fixed... maybe nothing released a silent update to correct it... for now it's working perfectly & I don't believe the launcher has anything to do with it

**Comment by codesalatdev** [comment]
The issue persists for me. I temporarily fixed it by removing Nothing Launcher, but after an OS update the issue reappeard.

**Comment by NiagaraSupport** [comment]
Thanks for the report, and I'm sorry to hear the issue persists.
Could someone test if the issue also occurs on other 3rd party launchers to give some clarification on what may be the cause? Assistance would be greatly appreciated.

**Comment by Auroria-code** [comment]
I am said Phone 1. I had an update to Android 14 today, the bug was there for me. Then the nothing Launcher had an update, problem gone, same for OPs phone 2. So this issue seems resolved by nothing.

**Comment by codesalatdev** [comment]
As @Auroria-code mentioned, this issue was solved with an update of the Nothing Launcher, which I received a few days after reporting that the issue persists. I guess they noticed it was doing something it shouldn't.
