### ISSUE TITLE
Elements on home screen disappear in swiping up (Nothin OS 3.0 / Nothing 2a)

### ISSUE THREAD

**Issue by dobidavi** [8bitPit/Niagara-Issues#3126]
### Describe the bug

Elements on home screen disappear in swiping up (Nothin OS 3.0 / Nothing 2a)

### Steps to reproduce

1. On Home screen 
2. Swipe Up from the very bottom of the screen.

Icons don't reappear unless another long swipe up is done

https://github.com/user-attachments/assets/2f8666e9-de6d-4b47-b454-fbabeb92e820

### Does the issue also occur with other 3rd-party launchers?

Problem occurs with other launchers

### Device name

Nothing Phone 2a

### Android version

Android 15

**Comment by TheBestPessimist** [comment]
This is not only for other launchers, this happens on my no longer updated pixel 4a, but only sometimes. It started happening after the winter/January Niagara update.

**Comment by contact-maximux** [comment]
niagra widget dissappear after swipe up in home screen. moto

**Comment by TFackler** [comment]
@TheBestPessimist Could you please send us an extended version of the screen recording?

Also if there are steps to reproduce the issue reliably, that would be very valuable for us.

**Comment by TFackler** [comment]
@contact-maximux Are you referring to the Niagara at-a-glance widget, or are you talking about custom widgets you have added to your home screen.

I think your issue might be a different one, so please open a new bug report and include a screen recording.

**Comment by contact-maximux** [comment]
@TFackler  custom widget. It does not matter which widget all kind of widget showing same DISSAPPEAR behavior

**Comment by Aaks17** [comment]
this is related to #3160

**Comment by Aaks17** [comment]
This issue is fixed with the new nothing os update

**Comment by dobidavi** [comment]
No, it's not fixed on my device (Nothing os update Pacman-V3.0-250114-1909-EEA)
