### ISSUE TITLE
Niagra Launcher Showing in Recents

### ISSUE THREAD

**Issue by palmuse** [8bitPit/Niagara-Issues#3234]
The launcher is appearing in my recents always. Interfering with the swipe back to last app and such features. This has been since that last update or two.

Version 1.13.7 (1307)

OnePlus 11
OS version: 15, Build: CPH2451_15.0.0.401(EX01)
Bootloader: unknown, VM: ART
Kernel: 5.15.149-android13-8-o-01121-g3180afd135ff
Brand: OnePlus, Model: CPH2451
Board: kalama, Manufacturer: OnePlus

SDK
Target: 35, Min: 28

**Comment by TFackler** [comment]
Thanks for reporting this. 

Have you set Niagara Launcher as your default launcher / home app?

We have recently changed something with how Niagara Launcher is labelled so that the system does not include it in the recent apps screen to fix a similar issue ([Recent-apps screen / app overview: Most recent app is transparent](https://help.niagaralauncher.app/article/174-bug-reports-on-androids-issue-tracker)).

**Comment by Maxr1998** [comment]
It usually shows in recent shortly after installing an update, or if it's not set as the default launcher. In the former case, removing it from recents once should resolve the issue. In the latter case, no real workaround exists at this time.

**Comment by palmuse** [comment]
Yes, I have Niagara set as my home app. I did think about this and tried to toggle the home app (default then back to Niagara), but this did not fix.

I can dismiss it from recents and it seems ti stay away for a bit, but eventually it shows again. Possibly whenever the app is restarted. OnePlus kills apps religiously. I have all the settings in place to prevent this but it restarts occassionally.

**Comment by palmuse** [comment]
This issue seems to have been resolved on my OnePlus 11. I cannot explain how it is resolved. Could be an OS level app was updated. Not sure.

**Comment by tjsuominen** [comment]
This also happens with my Google P8P. And the issue persists / reappears, no matter what I do (restart launcher, restart phone)... After a while, it pops up on the recent's. Annoying.

**Comment by palmuse** [comment]
@TFackler Sorry, I missed your email earlier. I have all of the optimizations turned off in my OnePlus already. Very aware of that issue. I did not have the app locked, so I am trying that now.

**Comment by guniens** [comment]
Hi @TFackler 
Sorry for tagging you, is there any news about this? I've the same problem on my P8 with A16 QPR1 Beta 1 (nothing to do with the beta as I had the same problem with A15).
Thanks in advance!

**Comment by weedy** [comment]
P10Pro on BP4A.251205.006.E1

I'm getting this fairly consistently. 


![Screenshot_20260111-211437.png](https://github.com/user-attachments/assets/0939ed42-035f-4566-a022-3e71d0375082)

**Comment by palmuse** [comment]
I also see that often. Back gesture returns to full home screen.

Maybe move this to a new issue as it does not seem to be related to the recents issue? The recents issue has resolved for me.

**Comment by w00ter** [comment]
After months of being plaged by this issue I was hoping a fix would be here already. It is such an annoying bug (A16). 

I hope this bump will bring it back to the attention of dev

**Comment by jimmyski** [comment]
Also experiencing this after the latest updated. 

Samsung Galaxy Z Fold 5
Android 16
One UI 8.0

I've used this launcher for years and never had an issue until the last update. It is set as my default launcher. I've tried setting a different default and then back to Niagara. I've tried reboots. Nothing clears it up. Very annoying.
