### ISSUE TITLE
Most used apps disappeared

### ISSUE THREAD

**Issue by berdzena** [8bitPit/Niagara-Issues#550]
When i restart launcher its showing favorites and most used app(in my case chrom) after lock/unlock the phone most used app disappears (sorry for bad English)   i don't know how to add screenshoots to show you. https://photos.app.goo.gl/xTxPGHfLDzRwNpxN9
https://photos.app.goo.gl/EyBo24hhDy7NXFE56

HUAWEI p8 lite 2017 stock emui 8.0

**Comment by 8bitPit** [comment]
Hey @berdzena how often does that happen to you? Can you reproduce it?

**Comment by Rod911** [comment]
Was wondering where my suggestions went, repeated his steps and can confirm they did come back. Reproducible.

**Comment by 8bitPit** [comment]
Thanks for posting the video, I'll take a look at the code who is responsible for updating most used apps.

**Comment by 8bitPit** [comment]
Btw, are you using the alpha version from Telegram or the beta from PlayStore?

**Comment by berdzena** [comment]
Beta from telegram

**Comment by 8bitPit** [comment]
Okay, maybe your just using them too infrequently, how often do you open them?

**Comment by berdzena** [comment]
For example chrom and YouTube.. About 3-5 times a day

**Comment by 8bitPit** [comment]
That seems often, so probably it's a bug, thx for letting me know :)

**Comment by berdzena** [comment]
After update.. Most used apps is working..
Thanks

**Comment by berdzena** [comment]
Ah... Sorry. same again.. Not working after unlocking phone

**Comment by sxg997** [comment]
The same happens to me.
Within few minutes of restarting Niagara, the recent apps section completely disappears.

**Comment by inbx** [comment]
Same thing for me. 
Lenovo P2, LineageOS 16.0
Niagara v. 0.7.8

**Comment by 8bitPit** [comment]
It should be fixed in v0.8.0. You can download a preview build here if you want to try it out: https://github.com/8bitPit/Niagara-Issues/releases

**Comment by OEssHRERLr770rGGLOH0** [comment]
Sorry to revive but I'm still experiencing the bug described in the first post. For me, it happens every time I update Niagara. Some apps disappear from the most used lists and at least one (Chrome) doesn't come back until I clear the app's data and start from scratch. A complete deal breaker imo.

**Comment by 8bitPit** [comment]
If you clear data, the whole usage system resets. The more you use Niagara without resetting it, the more stable the algorithm will be.
