### ISSUE TITLE
Only one recent app is shown after navigating away from home.

### ISSUE THREAD

**Issue by renevdvorst** [8bitPit/Niagara-Issues#905]
**Describe the bug**
Only one recent app is shown below the pinned apps. The option to limit recent apps is OFF. When using the option to restart the launcher, 4 recent apps are shown. However, when navigating away from the home screen, the launcher is reverted back to only 1 recent app again.

**To Reproduce**
Not sure what triggered this in the first place. However I can reliably:

1. Use option to restart launcher. See that 4 recents are shown.
2. Navigate to another app.
3. Go back to home screen. See that 1 recent is shown.

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2
 - Android version: Android One. Version 9. May 2019 security patch.

**Comment by Rod911** [comment]
Strange. This was supposed to have been fixed in v0.8.0 (#550)
Can you confirm that you have the latest build of Niagara? You can get it from [Niagara News
Channel](https://t.me/niagara_news) or [Github releases](https://github.com/8bitPit/Niagara-Issues/releases)

**Comment by renevdvorst** [comment]
I was indeed on 0.7.8 I did not realize the Play store was lagging behind. Installing the latest from Telegram did not fix the issue for me immediately, but after a clean install it is working as intended.
